/**
 * Export and clipboard utilities for Knowledge Center (Flashcards, Doc Cards, Notes).
 */
import type { FlashcardItem } from '@piwin/contracts';
import { expandItemToReviewCards, itemPreviewText } from '@piwin/flashcards';

/**
 * Formats a single flashcard as Markdown text.
 */
export function formatCardMarkdown(card: FlashcardItem): string {
  const lines: string[] = [
    `### Q: ${itemPreviewText(card) || card.front || ''}`,
    '',
    `**A:** ${card.back ?? card.text ?? ''}`,
  ];
  if (card.sourceFile) {
    const loc = typeof card.sourceLine === 'number' ? `:${card.sourceLine}` : '';
    lines.push('', `> 📄 *Source: ${card.sourceFile}${loc}*`);
  }
  if (card.sourceExcerpt) {
    lines.push('', `> *Excerpt: "${card.sourceExcerpt}"*`);
  }
  if (card.deck) {
    lines.push('', `\`#${card.deck}\``);
  }
  return lines.join('\n');
}

/**
 * Formats a deck of cards as a single Markdown document (Obsidian / Notion compatible).
 */
export function formatDeckMarkdown(deckTitle: string, cards: FlashcardItem[]): string {
  const header = `# 🗂️ ${deckTitle} (${cards.length} Cards)\n\n*Generated by piwin Knowledge Center*\n\n---\n\n`;
  const body = cards.map((card, idx) => `## Card ${idx + 1}\n\n${formatCardMarkdown(card)}`).join('\n\n---\n\n');
  return header + body;
}

/**
 * Formats cards as Anki-compatible TSV (Front, Back, Deck, Source).
 */
export function formatCardsAnkiTsv(cards: FlashcardItem[]): string {
  return cards
    .flatMap((item) => expandItemToReviewCards(item))
    .map((c) => {
      const front = c.front.replace(/\t/g, ' ').replace(/\n/g, '<br>');
      const back = c.back.replace(/\t/g, ' ').replace(/\n/g, '<br>');
      const deck = (c.deck || 'Default').replace(/\t/g, ' ');
      const source = (c.sourceFile ? `${c.sourceFile}${typeof c.sourceLine === 'number' ? `:${c.sourceLine}` : ''}` : '').replace(/\t/g, ' ');
      return `${front}\t${back}\t${deck}\t${source}`;
    })
    .join('\n');
}

/**
 * Downloads text as a file in the browser / client shell.
 */
export function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}

/**
 * Copies text to system clipboard.
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    if (navigator?.clipboard?.writeText) {
      await navigator.clipboard.writeText(text);
      return true;
    }
    return false;
  } catch {
    return false;
  }
}
