/**
 * Extension & plugin catalog aligned with native Piwin extensions and 4-tier compatibility tags.
 * Pure typography-first schema with no emoji icons.
 */
import type { MarketExtensionItem, MarketPluginItem } from './marketplace-types.js';

export const INITIAL_EXTENSIONS: MarketExtensionItem[] = [
  {
    id: 'goal',
    name: 'goal',
    version: '1.3.0',
    source: 'bundled',
    author: '@narumitw/pi-goal',
    category: 'workflow',
    bundled: true,
    installed: true,
    active: true,
    descriptionZh: 'Autonomous goal execution loop and tracking extension (@narumitw/pi-goal). 支持断点续行、阶段性交付物汇总与自主任务状态流转。',
    descriptionEn: 'Autonomous goal execution loop and tracking extension (@narumitw/pi-goal).',
    tools: ['goal_start', 'goal_status', 'goal_update'],
    hooks: ['turn_start', 'turn_end'],
    tier: 'compatible',
    degradations: [],
  },
  {
    id: 'path-guard',
    name: 'path-guard',
    version: '2.0.1',
    source: 'bundled',
    author: '内置 (Bundled)',
    category: 'guard',
    bundled: true,
    installed: true,
    active: true,
    descriptionZh: 'Block write/edit targeting secret-like paths (.env, keys, credentials). 实时拦截针对敏感目录与密钥文件的危险越权读写。',
    descriptionEn: 'Block write/edit targeting secret-like paths (.env, keys, credentials).',
    tools: ['guard_inspect_diff'],
    hooks: ['tool_execution_start'],
    tier: 'compatible',
    degradations: [],
  },
  {
    id: 'pi-deepseek-cache',
    name: 'pi-deepseek-cache',
    version: '1.0.4',
    source: 'user',
    author: '用户扩展 (User)',
    category: 'tools',
    bundled: false,
    installed: true,
    active: true,
    descriptionZh: 'DeepSeek Cache Optimization Extension. 针对长上下文提示词做缓存分片对齐，显著降低重复 Token 开销与首字延迟。',
    descriptionEn: 'DeepSeek Cache Optimization Extension for prompt cache alignment and latency reduction.',
    tools: ['deepseek_cache_optimize'],
    hooks: ['turn_start'],
    tier: 'compatible',
    degradations: [],
  },
  {
    id: 'questionnaire',
    name: 'questionnaire',
    version: '1.1.2',
    source: 'bundled',
    author: '内置 (Bundled)',
    category: 'workflow',
    bundled: true,
    installed: true,
    active: true,
    descriptionZh: 'Ask the user structured questions through Pi\'s native Extension UI. 在需求或方案存在歧义时向用户弹出多选/单选对齐卡片。',
    descriptionEn: 'Ask the user structured questions through Pi\'s native Extension UI.',
    tools: ['ask_question', 'dismiss_question'],
    hooks: ['agent_start'],
    tier: 'compatible',
    degradations: [],
  },
  {
    id: 'pi-build-ios-apps',
    name: 'pi-build-ios-apps',
    version: '1.2.0',
    source: 'pi-native',
    author: 'Pi 原生 (pi-native)',
    category: 'tools',
    bundled: false,
    installed: true,
    active: true,
    descriptionZh: 'iOS app build and simulator automation toolchain (extension). 提供 Xcode 构建排错、模拟器拉起与签名检查工具。',
    descriptionEn: 'iOS app build and simulator automation toolchain (extension).',
    tools: ['ios_build', 'ios_run'],
    hooks: ['tool_execution_start'],
    tier: 'compatible',
    degradations: [],
  },
  {
    id: 'pi-web-access',
    name: 'pi-web-access',
    version: '2.1.0',
    source: 'npm',
    author: '社区开源 • npm',
    category: 'tools',
    bundled: false,
    installed: false,
    active: false,
    descriptionZh: '高下载量社区扩展。提供网页抓取与搜索工具；终端快捷键在桌面端已自动静默忽略，核心能力完整可用。',
    descriptionEn: 'Web fetch and search suite. Shortcuts degraded gracefully in desktop.',
    tools: ['web_search', 'web_fetch'],
    hooks: ['turn_start'],
    tier: 'degraded',
    degradations: ['shortcut', 'custom-renderer'],
  },
  {
    id: 'pi-mcp-adapter',
    name: 'pi-mcp-adapter',
    version: '3.0.4',
    source: 'npm',
    author: '社区开源 • npm',
    category: 'tools',
    bundled: false,
    installed: false,
    active: false,
    descriptionZh: '核心 MCP 工具转接器。带自定义状态显示与命令，在桌面端作为标准卡片运行。',
    descriptionEn: 'Dynamic MCP adapter. Status headers no-oped; tools fully functional.',
    tools: ['mcp_proxy_call', 'mcp_list_servers'],
    hooks: ['agent_start', 'turn_end'],
    tier: 'degraded',
    degradations: ['tui-widget', 'slash-command-unlisted'],
  },
  {
    id: 'pi-powerline-footer',
    name: 'pi-powerline-footer',
    version: '1.0.0',
    source: 'git',
    author: '社区开源 • GitHub',
    category: 'tools',
    bundled: false,
    installed: false,
    active: false,
    descriptionZh: '纯终端 TUI 状态栏美化包，不提供任何 Agent 工具或可用能力，仅可在终端环境运行。',
    descriptionEn: 'Terminal TUI status bar only. Provides no tools; incompatible in desktop.',
    tools: [],
    hooks: ['status_render'],
    tier: 'incompatible',
    degradations: ['tui-custom-ui', 'theme'],
  },
];

export const INITIAL_PLUGINS: MarketPluginItem[] = [
  {
    id: 'fullstack-web-suite',
    name: 'Fullstack Web 专家插件包',
    version: '2.4.0',
    category: 'workflow',
    bundled: false,
    installed: false,
    descriptionZh: '打包 React/Next.js/Node 开发全套能力，预置 4 个核心 Skills 与 Lighthouse MCP 服务。',
    descriptionEn: 'Bundles React/Next.js skills with Lighthouse MCP testing.',
    skillsCount: 4,
    mcpCount: 1,
    secrets: [],
  },
  {
    id: 'github-ops-plugin',
    name: 'GitHub PR 与 Issue 联动插件',
    version: '1.5.0',
    category: 'tools',
    bundled: false,
    installed: false,
    descriptionZh: '自动化 GitHub Issue 关联、PR Diff 评审并生成标准化提交信息。',
    descriptionEn: 'Automated GitHub issue linking, review summaries, and PR commits.',
    skillsCount: 2,
    mcpCount: 1,
    secrets: [
      { name: 'GITHUB_TOKEN', label: 'GitHub Personal Access Token', required: true },
    ],
  },
  {
    id: 'database-architect',
    name: 'Postgres & Prisma 数据架构师',
    version: '1.2.0',
    category: 'tools',
    bundled: false,
    installed: false,
    descriptionZh: '深度理解数据库 Schema，支持自动迁移排错、SQL 查询慢查分析。',
    descriptionEn: 'Schema inspection, auto migration debugging, and SQL query analysis.',
    skillsCount: 3,
    mcpCount: 1,
    secrets: [
      { name: 'DATABASE_URL', label: 'Database Connection String', required: false },
    ],
  },
];
