#!/usr/bin/env python3
"""Apply the piwin installer design to the Tauri NSIS template.

Design goals (from WREN's review of the stock wizard):
  * no garbled CJK anywhere -> art regenerated by scripts/dev/gen-nsis-art.py
  * default = one-click passive install (Cursor / VS Code style), no wizard pages
  * the passive surface is a designed card, not the stock InstFiles page
  * /INTERACTIVE keeps the wizard, restyled to the same palette

Runs against apps/desktop/src-tauri/windows/installer.nsi, which is a pristine
copy of tauri-bundler's installer.nsi (v2.11.4). Every anchor is asserted.
"""

from __future__ import annotations

from pathlib import Path

TEMPLATE = (
    Path(__file__).resolve().parents[2]
    / "apps" / "desktop" / "src-tauri" / "windows" / "installer.nsi"
)

# --------------------------------------------------------------------------- #
# 1. Palette + DPI helpers, injected ahead of !include MUI2.nsh
# --------------------------------------------------------------------------- #

THEME_HEADER = r'''

; =============================================================================
; piwin Inkstone installer design
;
; Palette source: packages/theme/bundled/piwin-inkstone-ink/theme.json
; Both NSIS SetCtlColors and Win32 COLORREF want 0x00BBGGRR.
; Art: scripts/dev/gen-nsis-art.py  (renders nsis-sidebar.bmp / nsis-header.bmp)
; =============================================================================
!define PW_INK            "0x101214"  ; surface1 #141210
!define PW_INK_PLATE      "0x191D20"  ; surface3 #201d19
!define PW_IVORY          "0xDAE5EB"  ; text1    #ebe5da
!define PW_MUTED          "0x929DA5"  ; text2    #a59d92
!define PW_MUTED_DIM      "0x78838B"  ; text3    #8b8378
!define PW_MUTED_FAINT    "0x59626A"  ; text4    #6a6259
!define PW_VERMILION      "0x3D5AE2"  ; iris     #e25a3d
!define PW_ON_VERMILION   "0x070B1C"  ; onIris   #1c0b07

!define PW_FACE "Microsoft YaHei UI"
!define PW_FACE_FALLBACK "Microsoft YaHei"

; Every card variable lives here, above the helpers: NSIS resolves $vars at
; parse time, so a Var declared after its first use silently degrades to an
; unknown constant (warning 6000) and the layout maths collapses to zero.
Var PwDpi
Var PwHwnd
Var PwPad
Var PwInnerW
Var PwInnerH
Var PwTextX
Var PwTextW
Var PwContentW
Var PwFontTitle
Var PwFontBody
Var PwFontMeta
Var PwIconCtl
Var PwTitleCtl
Var PwSubCtl
Var PwMetaCtl
Var PwStatusCtl
Var PwBarCtl

; Card geometry, in logical (96 DPI) px. Scaled at runtime from
; GetDpiForWindow: a 2560x1440 panel at 150% must not get a 100% window.
!define PW_CARD_W   460
!define PW_CARD_H   270
!define PW_CARD_PAD  30
!define PW_ICON_BOX  52
!define PW_GAP_ICON  16

; MUI page chrome, dark
!define MUI_BGCOLOR "141210"
!define MUI_TEXTCOLOR "ebe5da"
!define MUI_HEADER_TRANSPARENT_TEXT
!define MUI_INSTFILESPAGE_COLORS "ebe5da 141210"
!define MUI_INSTFILESPAGE_PROGRESSBAR "smooth"
!define MUI_CUSTOMFUNCTION_GUIINIT PwDarkTitleBar
!define MUI_CUSTOMFUNCTION_UNGUIINIT un.PwDarkTitleBar

!define WM_SETFONT_PW 0x0030
!define STM_SETICON_PW 0x0170
!define PBM_SETBKCOLOR_PW 0x2001
!define PBM_SETBARCOLOR_PW 0x0409

Function PwDarkTitleBar
  ; DWMWA_USE_IMMERSIVE_DARK_MODE: 20 (Win10 20H1+/Win11), 19 (Win10 1809-1909)
  System::Call 'dwmapi::DwmSetWindowAttribute(p $HWNDPARENT, i 20, *i 1, i 4)'
  System::Call 'dwmapi::DwmSetWindowAttribute(p $HWNDPARENT, i 19, *i 1, i 4)'
  ; DWMWA_WINDOW_CORNER_PREFERENCE (33) = DWMWCP_ROUND (2)
  System::Call 'dwmapi::DwmSetWindowAttribute(p $HWNDPARENT, i 33, *i 2, i 4)'
FunctionEnd

Function un.PwDarkTitleBar
  System::Call 'dwmapi::DwmSetWindowAttribute(p $HWNDPARENT, i 20, *i 1, i 4)'
  System::Call 'dwmapi::DwmSetWindowAttribute(p $HWNDPARENT, i 19, *i 1, i 4)'
  System::Call 'dwmapi::DwmSetWindowAttribute(p $HWNDPARENT, i 33, *i 2, i 4)'
FunctionEnd

; $R0: logical px -> $R0: physical px for the window's current DPI.
Function PwScale
  IntOp $R0 $R0 * $PwDpi
  IntOp $R0 $R0 / 96
FunctionEnd

!macro PwPx LOGICAL
  StrCpy $R0 ${LOGICAL}
  Call PwScale
!macroend

; Hides a stock control. MUI parks some of them on the outer dialog and some
; inside the inner dialog, so try both parents.
!macro PwHide ID
  GetDlgItem $R0 $HWNDPARENT ${ID}
  ShowWindow $R0 0
  GetDlgItem $R0 $PwHwnd ${ID}
  ShowWindow $R0 0
!macroend

; $OUT = handle of control ID, searching the inner dialog then the outer one.
!macro PwCtl ID OUT
  GetDlgItem ${OUT} $PwHwnd ${ID}
  ${If} ${OUT} == 0
    GetDlgItem ${OUT} $HWNDPARENT ${ID}
  ${EndIf}
!macroend

; Drops a HFONT for the Inkstone UI face at LOGICAL px into OUT.
!macro PwFont LOGICAL WEIGHT OUT
  StrCpy $R0 ${LOGICAL}
  Call PwScale
  IntOp $R0 0 - $R0                                    ; negative = character height
  System::Call 'gdi32::CreateFontW(i r0, i 0, i 0, i 0, i ${WEIGHT}, i 0, i 0, i 0, i 134, i 0, i 0, i 5, i 0, w "${PW_FACE}") p .R1'
  ${If} $R1 == 0
    System::Call 'gdi32::CreateFontW(i r0, i 0, i 0, i 0, i ${WEIGHT}, i 0, i 0, i 0, i 134, i 0, i 0, i 5, i 0, w "${PW_FACE_FALLBACK}") p .R1'
  ${EndIf}
  StrCpy ${OUT} $R1
!macroend

'''

# --------------------------------------------------------------------------- #
# 2. One-click card + interactive wizard restyle, replacing the InstFiles hook
# --------------------------------------------------------------------------- #

CARD_BLOCK = r'''
; 7. Installation page
;
; Two surfaces:
;   * passive (default): one card, no wizard pages, no buttons
;       [icon]  piwin
;               私有 AI 智能体工作台
;       桌面外壳 · 宿主运行时 · 内置 Node
;       <status>
;       ┃━━━━━━━━━━━━━━━━━━━━━━━━━┃   live progress
;   * /INTERACTIVE: the normal wizard, restyled to the same palette.

; Restyles the wizard in the Inkstone palette. Geometry stays MUI's: its
; dialog-unit layout is already DPI correct, so this only re-colours.
Function PwWizardChrome
  StrCpy $PwHwnd 0
  !insertmacro PwHide 1256
  !insertmacro PwHide 1036
  !insertmacro PwHide 1045
  SetCtlColors $HWNDPARENT ${PW_IVORY} ${PW_INK}

  GetDlgItem $0 $HWNDPARENT 1037
  SetCtlColors $0 ${PW_IVORY} ${PW_INK}
  GetDlgItem $0 $HWNDPARENT 1038
  SetCtlColors $0 ${PW_MUTED} ${PW_INK}
  GetDlgItem $0 $HWNDPARENT 1201
  SetCtlColors $0 ${PW_IVORY} ${PW_INK}
  GetDlgItem $0 $HWNDPARENT 1202
  SetCtlColors $0 ${PW_MUTED} ${PW_INK}
  GetDlgItem $0 $HWNDPARENT 1019
  SetCtlColors $0 ${PW_IVORY} ${PW_INK_PLATE}

  ; Primary action in vermillion, everything else flat on ink.
  GetDlgItem $0 $HWNDPARENT 1
  System::Call 'uxtheme::SetWindowTheme(p r0, w "", w "")'
  SetCtlColors $0 ${PW_ON_VERMILION} ${PW_VERMILION}
  GetDlgItem $0 $HWNDPARENT 2
  System::Call 'uxtheme::SetWindowTheme(p r0, w "", w "")'
  SetCtlColors $0 ${PW_MUTED} ${PW_INK_PLATE}
  GetDlgItem $0 $HWNDPARENT 3
  System::Call 'uxtheme::SetWindowTheme(p r0, w "", w "")'
  SetCtlColors $0 ${PW_MUTED} ${PW_INK_PLATE}
  GetDlgItem $0 $HWNDPARENT 1001
  System::Call 'uxtheme::SetWindowTheme(p r0, w "", w "")'
  SetCtlColors $0 ${PW_MUTED} ${PW_INK_PLATE}
FunctionEnd

Function PwCard
  ; ---- dpi ----
  System::Call 'user32::GetDpiForWindow(p $HWNDPARENT) i .R0'
  StrCpy $PwDpi $R0
  ${If} $PwDpi < 96
    StrCpy $PwDpi 96
  ${EndIf}
  FindWindow $PwHwnd "#32770" "" $HWNDPARENT

  !insertmacro PwPx ${PW_CARD_PAD}
  StrCpy $PwPad $R0

  ; ---- size + centre on the work area (not the raw screen: taskbar) ----
  !insertmacro PwPx ${PW_CARD_W}
  StrCpy $R1 $R0
  !insertmacro PwPx ${PW_CARD_H}
  StrCpy $R2 $R0
  System::Alloc 16
  Pop $R3
  System::Call 'user32::SystemParametersInfoW(i 48, i 0, p r3, i 0)'   ; SPI_GETWORKAREA
  System::Call '*$R3(i .R4, i .R5, i .R6, i .R7)'
  System::Free $R3
  IntOp $R6 $R6 - $R4
  IntOp $R6 $R6 - $R1
  IntOp $R6 $R6 / 2
  IntOp $R6 $R6 + $R4
  IntOp $R7 $R7 - $R5
  IntOp $R7 $R7 - $R2
  IntOp $R7 $R7 / 2
  IntOp $R7 $R7 + $R5
  System::Call 'user32::SetWindowPos(p $HWNDPARENT, p 0, i r6, i r7, i r1, i r2, i 0x0004)'
  System::Call 'user32::SetWindowTextW(p $HWNDPARENT, w "piwin 安装程序")'

  ; ---- strip every piece of stock wizard chrome ----
  ; 1/2/3 = next/back/cancel, 1018/1044 = unused MUI statics, 1028/1256 =
  ; copyright, 1034 = header plate, 1036/1045 = etched separators,
  ; 1046 = header bitmap, 1200 = welcome bitmap, 1016 = detail list.
  !insertmacro PwHide 1
  !insertmacro PwHide 2
  !insertmacro PwHide 3
  !insertmacro PwHide 1016
  !insertmacro PwHide 1018
  !insertmacro PwHide 1028
  !insertmacro PwHide 1034
  !insertmacro PwHide 1036
  !insertmacro PwHide 1044
  !insertmacro PwHide 1045
  !insertmacro PwHide 1046
  !insertmacro PwHide 1200
  !insertmacro PwHide 1256

  ; ---- the inner dialog becomes the card (covers anything left behind) ----
  System::Alloc 16
  Pop $R3
  System::Call 'user32::GetClientRect(p $HWNDPARENT, p r3)'
  System::Call '*$R3(i .R4, i .R5, i .R6, i .R7)'
  System::Free $R3
  StrCpy $PwInnerW $R6
  StrCpy $PwInnerH $R7
  System::Call 'user32::SetWindowPos(p $PwHwnd, p 0, i r4, i r5, i r6, i r7, i 0x0004)'
  SetCtlColors $HWNDPARENT ${PW_IVORY} ${PW_INK}
  SetCtlColors $PwHwnd ${PW_IVORY} ${PW_INK}

  StrCpy $PwContentW $PwInnerW
  IntOp $PwContentW $PwContentW - $PwPad
  IntOp $PwContentW $PwContentW - $PwPad

  ; The card states its own line; per-file detail is noise at this size.
  SetDetailsPrint none

  ; ---- type ----
  !insertmacro PwFont 21 600 $PwFontTitle
  !insertmacro PwFont 12 400 $PwFontBody
  !insertmacro PwFont 11 400 $PwFontMeta

  ; ---- brand mark, straight out of the installer's own icon resource ----
  ; Resource 1 is the icon Tauri passed as MUI_ICON. LoadIcon sizes it for the
  ; display DPI, so no bitmap asset has to be shipped or extracted at runtime.
  System::Call 'user32::GetSystemMetrics(i 11) i .R1'    ; SM_CXICON
  System::Call 'kernel32::GetModuleHandleW(p 0) p .R2'
  System::Call 'user32::LoadIconW(p r2, p 1) p .R3'
  ${If} $R3 <> 0
    System::Call 'user32::CreateWindowExW(i 0, w "STATIC", w "", i 0x50000003, i $PwPad, i $PwPad, i r1, i r1, p $PwHwnd, i 0, i 0, i 0) p .R4'
    SendMessage $R4 ${STM_SETICON_PW} $R3 0
    StrCpy $PwIconCtl $R4
  ${EndIf}

  ; ---- text block, right of the mark ----
  StrCpy $PwTextX $PwPad
  !insertmacro PwPx ${PW_ICON_BOX}
  IntOp $PwTextX $PwTextX + $R0
  !insertmacro PwPx ${PW_GAP_ICON}
  IntOp $PwTextX $PwTextX + $R0
  StrCpy $PwTextW $PwInnerW
  IntOp $PwTextW $PwTextW - $PwTextX
  IntOp $PwTextW $PwTextW - $PwPad

  !insertmacro PwPx 34
  StrCpy $R1 $R0
  !insertmacro PwPx 28
  System::Call 'user32::CreateWindowExW(i 0, w "STATIC", w "piwin", i 0x50000000, i $PwTextX, i r1, i $PwTextW, i r0, p $PwHwnd, i 0, i 0, i 0) p .R2'
  StrCpy $PwTitleCtl $R2
  SendMessage $PwTitleCtl ${WM_SETFONT_PW} $PwFontTitle 1
  SetCtlColors $PwTitleCtl ${PW_IVORY} ${PW_INK}

  !insertmacro PwPx 66
  StrCpy $R1 $R0
  !insertmacro PwPx 22
  System::Call 'user32::CreateWindowExW(i 0, w "STATIC", w "私有 AI 智能体工作台", i 0x50000000, i $PwTextX, i r1, i $PwTextW, i r0, p $PwHwnd, i 0, i 0, i 0) p .R2'
  StrCpy $PwSubCtl $R2
  SendMessage $PwSubCtl ${WM_SETFONT_PW} $PwFontBody 1
  SetCtlColors $PwSubCtl ${PW_MUTED} ${PW_INK}

  !insertmacro PwPx 116
  StrCpy $R1 $R0
  !insertmacro PwPx 20
  System::Call 'user32::CreateWindowExW(i 0, w "STATIC", w "桌面外壳 · 宿主运行时 · 内置 Node", i 0x50000000, i $PwPad, i r1, i $PwContentW, i r0, p $PwHwnd, i 0, i 0, i 0) p .R2'
  StrCpy $PwMetaCtl $R2
  SendMessage $PwMetaCtl ${WM_SETFONT_PW} $PwFontMeta 1
  SetCtlColors $PwMetaCtl ${PW_MUTED_FAINT} ${PW_INK}

  ; ---- status line + progress bar, pinned to the bottom ----
  !insertmacro PwCtl 1006 $PwStatusCtl
  ${If} $PwStatusCtl <> 0
    !insertmacro PwPx 68
    IntOp $R1 $PwInnerH - $R0
    !insertmacro PwPx 22
    StrCpy $R2 $R0
    SendMessage $PwStatusCtl ${WM_SETFONT_PW} $PwFontMeta 1
    SendMessage $PwStatusCtl 0x000C 0 "STR:正在安装运行时组件，完成后将自动启动"
    SetCtlColors $PwStatusCtl ${PW_MUTED_DIM} ${PW_INK}
    System::Call 'user32::SetWindowPos(p $PwStatusCtl, p 0, i $PwPad, i r1, i $PwContentW, i r2, i 0x0004)'
  ${EndIf}

  !insertmacro PwCtl 1004 $PwBarCtl
  ${If} $PwBarCtl <> 0
    !insertmacro PwPx 38
    IntOp $R1 $PwInnerH - $R0
    !insertmacro PwPx 6
    StrCpy $R2 $R0
    System::Call 'uxtheme::SetWindowTheme(p $PwBarCtl, w "", w "")'
    SendMessage $PwBarCtl ${PBM_SETBKCOLOR_PW} 0 ${PW_INK_PLATE}
    SendMessage $PwBarCtl ${PBM_SETBARCOLOR_PW} 0 ${PW_VERMILION}
    System::Call 'user32::SetWindowPos(p $PwBarCtl, p 0, i $PwPad, i r1, i $PwContentW, i r2, i 0x0004)'
  ${EndIf}
FunctionEnd

Function InstFilesShow
  ${If} $PassiveMode = 1
    Call PwCard
  ${EndIf}
FunctionEnd

!define MUI_PAGE_CUSTOMFUNCTION_SHOW InstFilesShow
!insertmacro MUI_PAGE_INSTFILES
'''

ONINIT_OLD = '''Function .onInit
  ${GetOptions} $CMDLINE "/P" $PassiveMode
  ${IfNot} ${Errors}
    StrCpy $PassiveMode 1
  ${EndIf}
'''

ONINIT_NEW = '''Function .onInit
  ; One-click install by default (Cursor / VS Code style): every wizard page is
  ; skipped and the app launches itself once the card finishes.
  ;
  ; ${GetOptions} writes "" into its output variable when the switch is absent,
  ; so the default has to be established after parsing, never before.
  StrCpy $R0 ""
  ${GetOptions} $CMDLINE "/INTERACTIVE" $R0
  ${If} $R0 != ""
    StrCpy $PassiveMode 0
  ${Else}
    StrCpy $PassiveMode 1
  ${EndIf}

  ; /P pins passive mode for the silent uninstaller hand-off.
  ${GetOptions} $CMDLINE "/P" $R0
  ${IfNot} ${Errors}
    StrCpy $PassiveMode 1
  ${EndIf}
'''

SUCCESS_OLD = '''Function .onInstSuccess
  ; Check for `/R` flag only in silent and passive installers because
  ; GUI installer has a toggle for the user to (re)start the app
  ${If} $PassiveMode = 1
  ${OrIf} ${Silent}
    ${GetOptions} $CMDLINE "/R" $R0
    ${IfNot} ${Errors}
      ${GetOptions} $CMDLINE "/ARGS" $R0
      nsis_tauri_utils::RunAsUser "$INSTDIR\\${MAINBINARYNAME}.exe" "$R0"
    ${EndIf}
  ${EndIf}
FunctionEnd'''

SUCCESS_NEW = '''Function .onInstSuccess
  ; The card hands over to the app itself. The interactive wizard keeps its own
  ; "run piwin" finish-page toggle.
  ${If} $PassiveMode = 1
    nsis_tauri_utils::RunAsUser "$INSTDIR\\${MAINBINARYNAME}.exe" ""
  ${EndIf}
FunctionEnd'''

REINSTALL_OLD = '''Function PageReinstall
  ; Uninstall previous WiX installation if exists.'''

REINSTALL_NEW = '''Function PageReinstall
  ; One-click flow: refresh in place. The stock page would otherwise silently
  ; uninstall the previous version (hide the window, ExecWait the uninstaller,
  ; delete hundreds of MB) before the card ever appears.
  ${If} $PassiveMode = 1
    Abort
  ${EndIf}

  ; Uninstall previous WiX installation if exists.'''

PAGE_SHOW_HOOKS = (
    (
        '''!define MUI_PAGE_CUSTOMFUNCTION_PRE SkipIfPassive
!insertmacro MUI_PAGE_WELCOME''',
        '''!define MUI_PAGE_CUSTOMFUNCTION_PRE SkipIfPassive
!define MUI_PAGE_CUSTOMFUNCTION_SHOW PwWizardChrome
!insertmacro MUI_PAGE_WELCOME''',
    ),
    (
        '''!define MUI_PAGE_CUSTOMFUNCTION_PRE SkipIfPassive
!insertmacro MUI_PAGE_DIRECTORY''',
        '''!define MUI_PAGE_CUSTOMFUNCTION_PRE SkipIfPassive
!define MUI_PAGE_CUSTOMFUNCTION_SHOW PwWizardChrome
!insertmacro MUI_PAGE_DIRECTORY''',
    ),
    (
        '''!define MUI_PAGE_CUSTOMFUNCTION_PRE SkipIfPassive
!insertmacro MUI_PAGE_FINISH''',
        '''!define MUI_PAGE_CUSTOMFUNCTION_PRE SkipIfPassive
!define MUI_PAGE_CUSTOMFUNCTION_SHOW PwWizardChrome
!insertmacro MUI_PAGE_FINISH''',
    ),
)


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"anchor {label!r} matched {count} times (need exactly 1)")
    return text.replace(old, new, 1)


def main() -> int:
    source = TEMPLATE.read_text(encoding="utf-8")

    # 1. theme header, right before MUI2 so the MUI page macros see every define
    anchor = "!include MUI2.nsh"
    if source.count(anchor) != 1:
        raise SystemExit(f"expected exactly one {anchor!r}")
    source = source.replace(anchor, THEME_HEADER.strip() + "\n\n" + anchor, 1)

    # 2. the card replaces the stock InstFiles page hook
    card_start = source.index("; 7. Installation page\n")
    card_macro = "!insertmacro MUI_PAGE_INSTFILES"
    card_end = source.index(card_macro, card_start) + len(card_macro)
    source = source[:card_start] + CARD_BLOCK.strip() + source[card_end:]

    # 3. passive-by-default that actually sticks
    source = replace_once(source, ONINIT_OLD, ONINIT_NEW, ".onInit passive default")

    # 4. the card launches the app; the wizard keeps its finish-page toggle
    source = replace_once(source, SUCCESS_OLD, SUCCESS_NEW, ".onInstSuccess")

    # 5. one-click flow never detours through the maintenance page
    source = replace_once(source, REINSTALL_OLD, REINSTALL_NEW, "PageReinstall passive skip")

    # 6. wizard page SHOW hooks
    for old, new in PAGE_SHOW_HOOKS:
        source = replace_once(source, old, new, f"show hook: {old.splitlines()[-1]}")

    TEMPLATE.write_text(source, encoding="utf-8")
    print(f"wrote {TEMPLATE} ({len(source.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
